services:
  - type: web
    name: your-backend-service
    env: python
    buildCommand: |
      apt-get update && apt-get install -y cmake build-essential libboost-all-dev libgtk-3-dev
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    pythonVersion: 3.10
