services:
  - type: web
    name: face-recognition-backend
    env: python
     apt-get update && apt-get install -y cmake build-essential
      pip install -r requirements.txt
    startCommand: python app.py  
    pythonVersion: 3.10